export enum ActionType {
  DATA_PRODUCT = 'DATA_PRODUCT',
  FILTER_PRODUCT_JAWEL = 'FILTER_PRODUCT_JAWEL',
  FILTER_PRODUCT_MEN = 'FILTER_PRODUCT_MEN',
  FILTER_PRODUCT_WOMEN = 'FILTER_PRODUCT_WOMEN',
}
